-- MySQL Workbench Synchronization
-- Generated: 2024-03-30 21:12
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Vũ Khánh Quốc

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `note_taking_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

CREATE TABLE IF NOT EXISTS `note_taking_db`.`notes` (
  `id_notes` INT(11) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `directory` TEXT NULL DEFAULT NULL,
  `createAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_notes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `note_taking_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(10) CHARACTER SET 'macce' NOT NULL,
  `username` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isPremium` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
